### DISCUSSION TITLE
Spec Formalization: Custom Output Derivation for Function Signatures

### DISCUSSION THREAD

**Discussion by jacques-n** [substrait-io/substrait#32] [General]
Functions that work entirely with simple (non-compound) types typically have very simple semantics. For example: add(i32, i32) => i32. These kinds of functions have what is declared in function signatures as "direct" output type. For compound types, derivation strategies can be more complex. A couple of examples: 

A function such as `func(List<T>) =>T`
A function such as `func(decimal(p1, s1), decimal(p2,s2)) => decimal(max(p1+p2,38),min(s1,s2))`

To correctly validate plans, the function signatures and the Substrait specification must support these arbitrary output type derivation strategies. As such, we need some way to define the arbitrary logic associated with type derivation so that any time a function is used in a plan, the output type is clearly specified/determinate. So the question is: what is the best way to support this to be portable across systems in as simple a way as possible?

**Comment by wesm** [comment]
If the type derivations are to live outside of a Substrait expression, then in the general case, I beleive you would need to define a "simple" type derivation grammar for function signatures (for example, `list_append(v: list<T>, v: T) => list<T>`). The downside is that implementations have to implement that grammar

**Reply by jacques-n** [reply]
I was hoping we could find some kind of simple expression language that could be converted to various targets such c code, llvm bytecode, etc. I worry that a custom grammar would get turn into a language quickly and almost be a painful constraint for function developers. I spent a little time looking at some examples. For example, [decimal derivation behaviors](https://github.com/apache/arrow/blob/master/java/gandiva/src/main/java/org/apache/arrow/gandiva/evaluator/DecimalTypeUtil.java). In that case you have pretty simple math (including min/max).

I also looked at [another operation](https://github.com/dremio/dremio-oss/blob/5a22a0401f346e3168281ccb586a82d187660336/sabot/kernel/src/main/java/com/dremio/exec/expr/fn/impl/Mappify.java#L79) that I remember having custom derivation at Dremio. It uses loops/lists.

I also wonder if we need to be able to throw errors for some conditions which (I guess) would mean that the specific compound parameters are unbindable to that function.

**Reply by westonpace** [reply]
It's possible that parameterization takes us 90% of the way there and we can simply define functions for the remaining behaviors.  For example:

```
take_first:
    parameters:
        - T
    args:
        - LIST<T>
    output:
        type: T

add:
    parameters:
        - P1
        - S1
        - P2
        - S2
    args:
        - Decimal<P1, S1>
        - Decimal<P2, S2>
    output:
        function_name: "DECIMAL_PROMOTE"
        args:
            - P1
            - S1
            - P2
            - S2
```

Then extensions are welcome to define whatever "type functions" they want but the actual arithmetic doesn't have to be expressed in the plan itself.
