### ISSUE TITLE
[bug] concat:vchar is unusable

### ISSUE THREAD

**Issue by miretskiy** [substrait-io/substrait#802]
[concat:vchar](https://github.com/substrait-io/substrait/blob/098a67afb2c968f10cbe7994b18f5dfce72a6246/extensions/functions_string.yaml#L12) overload is unusable:
```
impls:
      - args:
          - value: "varchar<L1>"
            name: "input"
        variadic:
          min: 1
        options:
          null_handling:
            values: [ IGNORE_NULLS, ACCEPT_NULLS ]
        return: "varchar<L1>"
```
This overload can only be used to concatenate a single argument (a no-op) or nulls (a no-op).
This overload should be removed.
